
print (" ---------------------------------------------- ")
print ("|                                              |")
print ("|    Hello World                               |")
print ("|    Name : Grace Thomas                       |")
print ("|    Version : 01                              |")
print ("|                                              |")
print (" ---------------------------------------------- ")
print ("Hello World")
input ("Program paused - press enter to continue...")
print("Goodbye World")